server:
  port: ${fireman.server.port}
  servlet:
    context-path: /

spring:
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql:///firealarm
      username: ${fireman.database.username}
      password: ${fireman.database.password}
      driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  type-aliases-package: com.FireAlarm.pojo
  global-config:
    db-config:
      logic-delete-field: isDeleted
      id-type: auto
      table-prefix: alarm_
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  token:
    tokenExpiration: 120 #有效时间,单位分钟
    tokenSignKey: fireman123456



formverification:
  USER_IDCARD_LENGTH: 20
  USER_PASSWORD_LENGTH: 6


cors:
  IP: ${cors.IP}
  ADDRESS: ${cors.ADDRESS}