fireman:
  server:
    port: 8081

  database:
    username: root
    password: '#Include123'

cors:
  IP: 127.0.0.1
  PORT: 8088

redis:
  host: localhost
  port: 6379
  password: 123456


rabbitmq:
  host:  192.168.186.128
  port: 5672
  username: user
  password: 123456





firealarm:
  filepath:
    VIDEO_FILE_PATH: 'D:\try_java\FireAlarmBackend\src\main\resources\video'  # 相对路径
    PIC_FILE_PATH: 'D:\try_java\FireAlarmBackend\src\main\resources\image'