fireman:
  server:
    port: 8081

  database:
    username: root
    password: '#Include123'

cors:
  IP: 49.232.140.247
  PORT: 8088

redis:
  host: localhost
  port: 6379
  password: 123456



firealarm:
  filepath:
    VIDEO_FILE_PATH: '/var/FireAlarmBackend/resources/video'
    PIC_FILE_PATH: '/var/FireAlarmBackend/resources/image'
